name: CI/CD API

on:
  push:
    branches:
      - CI/CD

jobs:
  build-and-push-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push API Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/todo_api:latest -f Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo_api:latest

  deploy-api:
    runs-on: ubuntu-latest
    needs: build-and-push-api
    steps:
      - name: SSH into Server and Deploy API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/todo_api:latest
            docker network create todo_network || true
            docker stop todo_api || true
            docker rm todo_api || true
            docker run -d --name todo_api --network todo_network -p 8090:8090 ${{ secrets.DOCKERHUB_USERNAME }}/todo_api:latest
